gif_hacker/gif_hacker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls)
]

gif_hacker/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id_gif>/like/', views.like, name='like'),
    path('<int:id_gif>/deslike/', views.deslike, name='deslike')
]

gif_hacker/polls/models.py
from django.db import models
import requests
import json


# Create your models here.

class Vote (models.Model):
    id_gif = models.CharField(max_length=200)
    # vote_type: UP/DOWN 
    vote_type = models.CharField(max_length=200)

    def total_votos (self, id_gif):
        v = Vote.objects.filter(id_gif__exact=id_gif).count()
        return v

    def total_votos_up (self, id_gif):
        v = Vote.objects.filter(id_gif__exact=id_gif, vote_type__exact="UP").count()
        return v
    
    def total_votos_down (self, id_gif):
        v = Vote.objects.filter(id_gif__exact=id_gif, vote_type__exact="DOWN").count()
        return v
    
    def ordenar (self, describe):
        votes = Vote.objects.all()
    
        # Carregamento/vinculação dos votos registrados na database aos gifs extraídos da API

        for vote in votes:
            for d in describe:
                if (vote.id_gif == d['id']):
                    d['votos_total'] = Vote.total_votos(self=0, id_gif=vote.id_gif)
                    d['votos_up'] = Vote.total_votos_up(self=0, id_gif=vote.id_gif)
                    d['votos_down'] = Vote.total_votos_down(self=0, id_gif=vote.id_gif)
        
        sorted_describe = sorted(describe, key = lambda y : (-y.get('votos_up', 0), y.get('votos_down', 0)))
        
        return sorted_describe
    
    def request (self, apikey, lmt, search_term):
        # Requisição GET para carregar os gifs 
        response = requests.get("https://api.tenor.com/v1/search?q=%s&key=%s&limit=%s&media_filter=minimal&ar_range=wide" % (search_term, apikey, lmt))

        if response.status_code == 200:
            # Carrega os gifs, reparte o json em partes úteis e gera um novo json somente com as informações necessárias. 
            result = json.loads(response.text)
            describe = result['results']
        else:
            return 404
        
        return describe

gif_hacker/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.http import QueryDict
from django.shortcuts import render
from .models import Vote

def index (request):
    # Insira os paramêtros de busca (chave de acesso, limite e o termo de busca) para realizar a requisição na API TENOR
    describe = Vote.request(self=0, apikey="LIVDSRZULELA", lmt=20, search_term = "HACKER")
    
    if (describe == 404):
        message_error = 'Ocorreu um erro inesperado na busca pelos seus gifs, cheque as suas credencias de acesso a API em polls/views.py'
        return render(request, 'polls/index.html', message_error)
    else:
        # Vinculação das curtidas e Ordenação por número de curtidas
        describe = Vote.ordenar(self=0, describe=describe)

        context = {'describes': describe}
        return render(request, 'polls/index.html', context)

def like(request, id_gif):
    v = Vote(id_gif=id_gif, vote_type='UP')
    v.save()
    return index(request)

def deslike(request, id_gif):
    v = Vote(id_gif=id_gif, vote_type='DOWN')
    v.save()
    return index(request)

gif_hacker/polls/templates/polls/copy_index.html
{% block content %}
    {% for describe in describes %}
    <div class="tenor-gif-embed" data-postid="{{describe.id}}" data-share-method="host" data-width="50%">
        <a href="{{ describe.itemurl }}"> {{ describe.title }} </a> from 
        <a href="https://tenor.com/search/hacker-gifs">Hacker GIFs</a></div>
    </div>
    {% endfor %}
{% endblock %}

<script type="text/javascript" async src="https://tenor.com/embed.js"></script>


<section class="card">
    <div class="card-header">
      <img
        src="https://images-na.ssl-images-amazon.com/images/I/91pFFPCBf5L._AC_SX522_.jpg"
        alt="furniture"
      />
    </div>
    <div class="card-body">
      <div class="card-content">
        <div>
          <h1>Transitions in UX Design</h1>
          <h2>IN DESIGN & PRINTS</h2>
        </div>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit.
          Doloremque omnis, autem possimus nam libero dignissimos! Assumenda
          consequatur, nisi repellat sint eos impedit non mollitia! Deleniti
          provident aperiam corrupti obcaecati totam!
        </p>
      </div>
      <div class="card-footer">
        <div>aprove</div>
        <a href="#"><div>reprove</div></a>
      </div>
    </div>
  </section>

gif_hacker/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    
    <title>CHD</title>
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;600;669;700;800;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />
    <style type="text/css">
        body {
            background-color: #00090cf5;
            margin: 0;
            font-family: 'Orbitron', sans-serif;
            }
  
        .navbar {
            background-color: rgb(230, 233, 231);
            padding: 15px;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        
        .navbar-title {
            font-weight: bold;
            font-size: 25px;
        }
        
        .navbar-menu {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        
        .navbar-menu ul {
            list-style: none;
            display: flex;
        }
        
        .navbar-menu li {
            margin: 0px 5px;
            cursor: pointer;
        }
        
        #active {
            color: grey;
        }
        
        .navbar-menu li:hover {
            color: grey;
        }
        
        .navbar-menu i {
            margin-left: 10px;
            font-size: 14px;
            cursor: pointer;
        }
        
        .navbar-menu i:hover {
            color: grey;
        }
        
        .header {
            background-color: black;
            background-size: cover;
            background-repeat: no-repeat;
            height: 200px;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        
        .header div {
            background-color: white;
            padding: 20px 40px;
            font-size: 30px;
        }
        
        .cards {
            display: flex;
            flex-wrap: wrap;
            justify-content: flex-end;
        }
        
        .card {
            width: 500px;
            margin: 35px;
        }
        
        .card-header img {
            width: 100%;
        }
        
        .card-body {
            text-align: center;
            padding: 15px 25px;
            background-color: white;
        }
        
        .card-content h1 {
            font-size: 20px;
            margin: 0;
        }
        #votos a{ 
            margin-top:20px;
            margin-bottom:20px;
            display: flex;
            align-items: center;
            text-decoration-style: none;
            background-color: black !important;
        }
        a:hover {
            color: gray(158, 28, 190);
        }
        .card-content h2 {
            margin-top: 5px;
            font-size: 12px;
            font-weight: 100;
            color: grey;
        }
        
        .card-content p {
            font-size: 17px;
        }
        
        .card-footer {
            display: flex;
            font-size: 12px;
            justify-content: space-between;
            color: grey;
        }
        .card-like {
            display: flex;
            font-size: 20px;
            justify-content: space-between;
            color: rgb(1, 11, 15);
        }
        .card-like a {
            color: rgb(1, 11, 15);
        }
        .card-like a:hover{
            color: gray;
        }
        /**/
        .card-footer a {
            text-decoration: none;
            color: black !important;
        }
        /**/
        
        footer {
            background-color: rgb(253, 255, 253);
            color: black;
            text-align: center;
            padding: 90px 90px 80px;
        }
        
        footer p {
            font-size: 20px;
            margin: 0;
        }
        footer a {
            color: black;
            text-decoration: none;
        }
        footer a:hover{
            color: gray;
        }
        .zoom {
            padding: 10px;
            background-color: black;
            transition: transform .2s; /* Animation */
            margin: 0 auto;
            box-shadow: 0 10px 50px 0 rgba(0, 0, 0, 0.5);
        }
        .zoom:hover {
            transform: scale(0.9); /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
        }
        .fast-transition {
            position: relative; /* For positioning the pseudo-element */
            box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.3);
        }

        .fast-transition::before {
        /* Position the pseudo-element. */
        content: ' ';
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;

        /* Create the box shadow at expanded size. */
        box-shadow: 0 10px 50px 0 rgba(0, 0, 0, 0.5);

        /* Hidden by default. */
        opacity: 0;
        transition: opacity 500ms;
        }

        .fast-transition:hover::before {
        /* Show the pseudo-element on hover. */
        opacity: 1;
        }
    </style>
  </head>
  <body>
    <!-- Menu principal -->
    <nav class="navbar">
      <div class="navbar-title">Central Hacker de GIF'S</div>
      <!-- <div class="navbar-menu">
      </div> -->
    </nav>

    <header class="header">
      <div class="">
        A sua central dos melhores gifs hackers!
      </div>
    </header>
    
    {% if message_error %}
      <div class="alert alert-warning" role="alert">
        <span class="material-icons">
            {{message_error}}
        </span>
        <h4 class="alert-heading">Erro de conexão</h4>
        <p> {{message_error}} </p>
      </div>
    {% else %}
    <main class="cards">
    {% for describe in describes %}
    
      <section class="card zoom">
        <div class="card-header">
            <div class="tenor-gif-embed" data-postid="{{describe.id}}" data-share-method="host" data-width="100%">
                <a href="{{ describe.itemurl }}"> {{ describe.title }} </a> from 
                <a href="https://tenor.com/search/hacker-gifs">Hacker GIFs</a>
            </div>
        </div>
        <div class="card-body">
          <div class="card-content">
            <div class="card-like">
                <a href="{% url 'polls:like' describe.id %}">
                    <div>
                        <span class="material-icons">
                            thumb_up
                        </span>
                    </div>
                </a>
            
                <a href="{% url 'polls:deslike' describe.id %}">
                    <div>
                        <span class="material-icons">
                            thumb_down
                        </span>
                    </div>
                </a>
            </div>
            <div id='votos'>
                {% if describe.votos_up > 0 or describe.votos_down > 0 %}
                    <div>
                        <span class="material-icons"> thumbs_up_down </span>
                        Total de votos: <strong>{{describe.votos_total}}</strong>
                    </div>
                {% else %}
                    <div> <strong>Nenhum voto ainda :(</strong></div>
                {%endif%}
            </div>
          </div>
          <div class="card-footer">
              {% if describe.votos_up > 0 %}
                <div> <strong>{{describe.votos_up}} hacker(s) votaram como favorito!</strong></div>
              {%endif%}
              
              {% if describe.votos_down != Null and  describe.votos_down > 0 %}
                <div> <strong>{{describe.votos_down}} hacker(s) não gostaram ... </strong></div>
              {%endif%}
          </div>
        </div>
      </section>
    {% endfor %}

    </main>
    {% endif %}
    <footer>
      <div>
        <a href="https://www.linkedin.com/in/luan-meira-083753111" target="_blank">
            <h1>LinkedIn</h1>
        </a>
        <a href="https://www.github.com/luanSaid" target="_blank">
            <h2>Github</h2>
        </a>
        <h3>Email</h3> <p> luansaidmeira@gmail.com</p>
      </div>
    </footer>
    <script type="text/javascript" async src="https://tenor.com/embed.js"></script>
    <script src="iconic.min.js"></script>
  </body>
</html>